# coding: utf-8

"""
    Blackfynn Swagger

    Swagger documentation for the Blackfynn api  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class CollaboratorChanges(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'changes': 'dict(str, ChangeResponse)',
        'counts': 'CollaboratorCounts'
    }

    attribute_map = {
        'changes': 'changes',
        'counts': 'counts'
    }

    def __init__(self, changes=None, counts=None):  # noqa: E501
        """CollaboratorChanges - a model defined in OpenAPI"""  # noqa: E501

        self._changes = None
        self._counts = None
        self.discriminator = None

        self.changes = changes
        self.counts = counts

    @property
    def changes(self):
        """Gets the changes of this CollaboratorChanges.  # noqa: E501


        :return: The changes of this CollaboratorChanges.  # noqa: E501
        :rtype: dict(str, ChangeResponse)
        """
        return self._changes

    @changes.setter
    def changes(self, changes):
        """Sets the changes of this CollaboratorChanges.


        :param changes: The changes of this CollaboratorChanges.  # noqa: E501
        :type: dict(str, ChangeResponse)
        """
        if changes is None:
            raise ValueError("Invalid value for `changes`, must not be `None`")  # noqa: E501

        self._changes = changes

    @property
    def counts(self):
        """Gets the counts of this CollaboratorChanges.  # noqa: E501


        :return: The counts of this CollaboratorChanges.  # noqa: E501
        :rtype: CollaboratorCounts
        """
        return self._counts

    @counts.setter
    def counts(self, counts):
        """Sets the counts of this CollaboratorChanges.


        :param counts: The counts of this CollaboratorChanges.  # noqa: E501
        :type: CollaboratorCounts
        """
        if counts is None:
            raise ValueError("Invalid value for `counts`, must not be `None`")  # noqa: E501

        self._counts = counts

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CollaboratorChanges):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
