# coding: utf-8

"""
    Blackfynn Swagger

    Swagger documentation for the Blackfynn api  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class FileContent(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        's3key': 'str',
        'updated_at': 'datetime',
        'size': 'int',
        's3bucket': 'str',
        'file_type': 'FileType',
        'id': 'int',
        'md5': 'str',
        'object_type': 'FileObjectType',
        'created_at': 'datetime',
        'package_id': 'str'
    }

    attribute_map = {
        'name': 'name',
        's3key': 's3key',
        'updated_at': 'updatedAt',
        'size': 'size',
        's3bucket': 's3bucket',
        'file_type': 'fileType',
        'id': 'id',
        'md5': 'md5',
        'object_type': 'objectType',
        'created_at': 'createdAt',
        'package_id': 'packageId'
    }

    def __init__(self, name=None, s3key=None, updated_at=None, size=None, s3bucket=None, file_type=None, id=None, md5=None, object_type=None, created_at=None, package_id=None):  # noqa: E501
        """FileContent - a model defined in OpenAPI"""  # noqa: E501

        self._name = None
        self._s3key = None
        self._updated_at = None
        self._size = None
        self._s3bucket = None
        self._file_type = None
        self._id = None
        self._md5 = None
        self._object_type = None
        self._created_at = None
        self._package_id = None
        self.discriminator = None

        self.name = name
        self.s3key = s3key
        self.updated_at = updated_at
        self.size = size
        self.s3bucket = s3bucket
        self.file_type = file_type
        self.id = id
        if md5 is not None:
            self.md5 = md5
        self.object_type = object_type
        self.created_at = created_at
        self.package_id = package_id

    @property
    def name(self):
        """Gets the name of this FileContent.  # noqa: E501


        :return: The name of this FileContent.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this FileContent.


        :param name: The name of this FileContent.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def s3key(self):
        """Gets the s3key of this FileContent.  # noqa: E501


        :return: The s3key of this FileContent.  # noqa: E501
        :rtype: str
        """
        return self._s3key

    @s3key.setter
    def s3key(self, s3key):
        """Sets the s3key of this FileContent.


        :param s3key: The s3key of this FileContent.  # noqa: E501
        :type: str
        """
        if s3key is None:
            raise ValueError("Invalid value for `s3key`, must not be `None`")  # noqa: E501

        self._s3key = s3key

    @property
    def updated_at(self):
        """Gets the updated_at of this FileContent.  # noqa: E501


        :return: The updated_at of this FileContent.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this FileContent.


        :param updated_at: The updated_at of this FileContent.  # noqa: E501
        :type: datetime
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")  # noqa: E501

        self._updated_at = updated_at

    @property
    def size(self):
        """Gets the size of this FileContent.  # noqa: E501


        :return: The size of this FileContent.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this FileContent.


        :param size: The size of this FileContent.  # noqa: E501
        :type: int
        """
        if size is None:
            raise ValueError("Invalid value for `size`, must not be `None`")  # noqa: E501

        self._size = size

    @property
    def s3bucket(self):
        """Gets the s3bucket of this FileContent.  # noqa: E501


        :return: The s3bucket of this FileContent.  # noqa: E501
        :rtype: str
        """
        return self._s3bucket

    @s3bucket.setter
    def s3bucket(self, s3bucket):
        """Sets the s3bucket of this FileContent.


        :param s3bucket: The s3bucket of this FileContent.  # noqa: E501
        :type: str
        """
        if s3bucket is None:
            raise ValueError("Invalid value for `s3bucket`, must not be `None`")  # noqa: E501

        self._s3bucket = s3bucket

    @property
    def file_type(self):
        """Gets the file_type of this FileContent.  # noqa: E501


        :return: The file_type of this FileContent.  # noqa: E501
        :rtype: FileType
        """
        return self._file_type

    @file_type.setter
    def file_type(self, file_type):
        """Sets the file_type of this FileContent.


        :param file_type: The file_type of this FileContent.  # noqa: E501
        :type: FileType
        """
        if file_type is None:
            raise ValueError("Invalid value for `file_type`, must not be `None`")  # noqa: E501

        self._file_type = file_type

    @property
    def id(self):
        """Gets the id of this FileContent.  # noqa: E501


        :return: The id of this FileContent.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FileContent.


        :param id: The id of this FileContent.  # noqa: E501
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def md5(self):
        """Gets the md5 of this FileContent.  # noqa: E501


        :return: The md5 of this FileContent.  # noqa: E501
        :rtype: str
        """
        return self._md5

    @md5.setter
    def md5(self, md5):
        """Sets the md5 of this FileContent.


        :param md5: The md5 of this FileContent.  # noqa: E501
        :type: str
        """

        self._md5 = md5

    @property
    def object_type(self):
        """Gets the object_type of this FileContent.  # noqa: E501


        :return: The object_type of this FileContent.  # noqa: E501
        :rtype: FileObjectType
        """
        return self._object_type

    @object_type.setter
    def object_type(self, object_type):
        """Sets the object_type of this FileContent.


        :param object_type: The object_type of this FileContent.  # noqa: E501
        :type: FileObjectType
        """
        if object_type is None:
            raise ValueError("Invalid value for `object_type`, must not be `None`")  # noqa: E501

        self._object_type = object_type

    @property
    def created_at(self):
        """Gets the created_at of this FileContent.  # noqa: E501


        :return: The created_at of this FileContent.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this FileContent.


        :param created_at: The created_at of this FileContent.  # noqa: E501
        :type: datetime
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def package_id(self):
        """Gets the package_id of this FileContent.  # noqa: E501


        :return: The package_id of this FileContent.  # noqa: E501
        :rtype: str
        """
        return self._package_id

    @package_id.setter
    def package_id(self, package_id):
        """Sets the package_id of this FileContent.


        :param package_id: The package_id of this FileContent.  # noqa: E501
        :type: str
        """
        if package_id is None:
            raise ValueError("Invalid value for `package_id`, must not be `None`")  # noqa: E501

        self._package_id = package_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FileContent):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
