# coding: utf-8

"""
    Blackfynn Swagger

    Swagger documentation for the Blackfynn api  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class GraphNodePropertiesDTO(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'category': 'str',
        'properties': 'list[GraphNodePropertyDTO]'
    }

    attribute_map = {
        'category': 'category',
        'properties': 'properties'
    }

    def __init__(self, category=None, properties=None):  # noqa: E501
        """GraphNodePropertiesDTO - a model defined in OpenAPI"""  # noqa: E501

        self._category = None
        self._properties = None
        self.discriminator = None

        self.category = category
        self.properties = properties

    @property
    def category(self):
        """Gets the category of this GraphNodePropertiesDTO.  # noqa: E501


        :return: The category of this GraphNodePropertiesDTO.  # noqa: E501
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this GraphNodePropertiesDTO.


        :param category: The category of this GraphNodePropertiesDTO.  # noqa: E501
        :type: str
        """
        if category is None:
            raise ValueError("Invalid value for `category`, must not be `None`")  # noqa: E501

        self._category = category

    @property
    def properties(self):
        """Gets the properties of this GraphNodePropertiesDTO.  # noqa: E501


        :return: The properties of this GraphNodePropertiesDTO.  # noqa: E501
        :rtype: list[GraphNodePropertyDTO]
        """
        return self._properties

    @properties.setter
    def properties(self, properties):
        """Sets the properties of this GraphNodePropertiesDTO.


        :param properties: The properties of this GraphNodePropertiesDTO.  # noqa: E501
        :type: list[GraphNodePropertyDTO]
        """
        if properties is None:
            raise ValueError("Invalid value for `properties`, must not be `None`")  # noqa: E501

        self._properties = properties

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GraphNodePropertiesDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
