# coding: utf-8

"""
    Blackfynn Swagger

    Swagger documentation for the Blackfynn api  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class PagedResponseTimeSeriesLayer(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'limit': 'int',
        'offset': 'int',
        'results': 'list[Object]'
    }

    attribute_map = {
        'limit': 'limit',
        'offset': 'offset',
        'results': 'results'
    }

    def __init__(self, limit=None, offset=None, results=None):  # noqa: E501
        """PagedResponseTimeSeriesLayer - a model defined in OpenAPI"""  # noqa: E501

        self._limit = None
        self._offset = None
        self._results = None
        self.discriminator = None

        self.limit = limit
        self.offset = offset
        self.results = results

    @property
    def limit(self):
        """Gets the limit of this PagedResponseTimeSeriesLayer.  # noqa: E501


        :return: The limit of this PagedResponseTimeSeriesLayer.  # noqa: E501
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this PagedResponseTimeSeriesLayer.


        :param limit: The limit of this PagedResponseTimeSeriesLayer.  # noqa: E501
        :type: int
        """
        if limit is None:
            raise ValueError("Invalid value for `limit`, must not be `None`")  # noqa: E501

        self._limit = limit

    @property
    def offset(self):
        """Gets the offset of this PagedResponseTimeSeriesLayer.  # noqa: E501


        :return: The offset of this PagedResponseTimeSeriesLayer.  # noqa: E501
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this PagedResponseTimeSeriesLayer.


        :param offset: The offset of this PagedResponseTimeSeriesLayer.  # noqa: E501
        :type: int
        """
        if offset is None:
            raise ValueError("Invalid value for `offset`, must not be `None`")  # noqa: E501

        self._offset = offset

    @property
    def results(self):
        """Gets the results of this PagedResponseTimeSeriesLayer.  # noqa: E501


        :return: The results of this PagedResponseTimeSeriesLayer.  # noqa: E501
        :rtype: list[Object]
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this PagedResponseTimeSeriesLayer.


        :param results: The results of this PagedResponseTimeSeriesLayer.  # noqa: E501
        :type: list[Object]
        """
        if results is None:
            raise ValueError("Invalid value for `results`, must not be `None`")  # noqa: E501

        self._results = results

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PagedResponseTimeSeriesLayer):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
