# coding: utf-8

"""
    Blackfynn Swagger

    Swagger documentation for the Blackfynn api  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ProxyTargetLinkRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'link_target': 'str',
        'relationship_type': 'str',
        'relationship_direction': 'ProxyRelationshipDirection'
    }

    attribute_map = {
        'link_target': 'linkTarget',
        'relationship_type': 'relationshipType',
        'relationship_direction': 'relationshipDirection'
    }

    def __init__(self, link_target=None, relationship_type=None, relationship_direction=None):  # noqa: E501
        """ProxyTargetLinkRequest - a model defined in OpenAPI"""  # noqa: E501

        self._link_target = None
        self._relationship_type = None
        self._relationship_direction = None
        self.discriminator = None

        self.link_target = link_target
        self.relationship_type = relationship_type
        self.relationship_direction = relationship_direction

    @property
    def link_target(self):
        """Gets the link_target of this ProxyTargetLinkRequest.  # noqa: E501


        :return: The link_target of this ProxyTargetLinkRequest.  # noqa: E501
        :rtype: str
        """
        return self._link_target

    @link_target.setter
    def link_target(self, link_target):
        """Sets the link_target of this ProxyTargetLinkRequest.


        :param link_target: The link_target of this ProxyTargetLinkRequest.  # noqa: E501
        :type: str
        """
        if link_target is None:
            raise ValueError("Invalid value for `link_target`, must not be `None`")  # noqa: E501

        self._link_target = link_target

    @property
    def relationship_type(self):
        """Gets the relationship_type of this ProxyTargetLinkRequest.  # noqa: E501


        :return: The relationship_type of this ProxyTargetLinkRequest.  # noqa: E501
        :rtype: str
        """
        return self._relationship_type

    @relationship_type.setter
    def relationship_type(self, relationship_type):
        """Sets the relationship_type of this ProxyTargetLinkRequest.


        :param relationship_type: The relationship_type of this ProxyTargetLinkRequest.  # noqa: E501
        :type: str
        """
        if relationship_type is None:
            raise ValueError("Invalid value for `relationship_type`, must not be `None`")  # noqa: E501

        self._relationship_type = relationship_type

    @property
    def relationship_direction(self):
        """Gets the relationship_direction of this ProxyTargetLinkRequest.  # noqa: E501


        :return: The relationship_direction of this ProxyTargetLinkRequest.  # noqa: E501
        :rtype: ProxyRelationshipDirection
        """
        return self._relationship_direction

    @relationship_direction.setter
    def relationship_direction(self, relationship_direction):
        """Sets the relationship_direction of this ProxyTargetLinkRequest.


        :param relationship_direction: The relationship_direction of this ProxyTargetLinkRequest.  # noqa: E501
        :type: ProxyRelationshipDirection
        """
        if relationship_direction is None:
            raise ValueError("Invalid value for `relationship_direction`, must not be `None`")  # noqa: E501

        self._relationship_direction = relationship_direction

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProxyTargetLinkRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
