# coding: utf-8

"""
    Blackfynn Swagger

    Swagger documentation for the Blackfynn api  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class TimeSeriesLayer(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'description': 'str',
        'color': 'str',
        'id': 'int',
        'time_series_id': 'str'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'color': 'color',
        'id': 'id',
        'time_series_id': 'timeSeriesId'
    }

    def __init__(self, name=None, description=None, color=None, id=None, time_series_id=None):  # noqa: E501
        """TimeSeriesLayer - a model defined in OpenAPI"""  # noqa: E501

        self._name = None
        self._description = None
        self._color = None
        self._id = None
        self._time_series_id = None
        self.discriminator = None

        self.name = name
        if description is not None:
            self.description = description
        if color is not None:
            self.color = color
        self.id = id
        self.time_series_id = time_series_id

    @property
    def name(self):
        """Gets the name of this TimeSeriesLayer.  # noqa: E501


        :return: The name of this TimeSeriesLayer.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TimeSeriesLayer.


        :param name: The name of this TimeSeriesLayer.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this TimeSeriesLayer.  # noqa: E501


        :return: The description of this TimeSeriesLayer.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this TimeSeriesLayer.


        :param description: The description of this TimeSeriesLayer.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def color(self):
        """Gets the color of this TimeSeriesLayer.  # noqa: E501


        :return: The color of this TimeSeriesLayer.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this TimeSeriesLayer.


        :param color: The color of this TimeSeriesLayer.  # noqa: E501
        :type: str
        """

        self._color = color

    @property
    def id(self):
        """Gets the id of this TimeSeriesLayer.  # noqa: E501


        :return: The id of this TimeSeriesLayer.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TimeSeriesLayer.


        :param id: The id of this TimeSeriesLayer.  # noqa: E501
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def time_series_id(self):
        """Gets the time_series_id of this TimeSeriesLayer.  # noqa: E501


        :return: The time_series_id of this TimeSeriesLayer.  # noqa: E501
        :rtype: str
        """
        return self._time_series_id

    @time_series_id.setter
    def time_series_id(self, time_series_id):
        """Sets the time_series_id of this TimeSeriesLayer.


        :param time_series_id: The time_series_id of this TimeSeriesLayer.  # noqa: E501
        :type: str
        """
        if time_series_id is None:
            raise ValueError("Invalid value for `time_series_id`, must not be `None`")  # noqa: E501

        self._time_series_id = time_series_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TimeSeriesLayer):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
