# coding: utf-8

"""
    Blackfynn Swagger

    Swagger documentation for the Blackfynn api  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class User(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'updated_at': 'datetime',
        'email': 'str',
        'url': 'str',
        'is_super_admin': 'bool',
        'preferred_organization_id': 'int',
        'color': 'str',
        'last_name': 'str',
        'first_name': 'str',
        'id': 'int',
        'authy_id': 'int',
        'status': 'bool',
        'created_at': 'datetime',
        'credential': 'str',
        'node_id': 'str',
        'password': 'str'
    }

    attribute_map = {
        'updated_at': 'updatedAt',
        'email': 'email',
        'url': 'url',
        'is_super_admin': 'isSuperAdmin',
        'preferred_organization_id': 'preferredOrganizationId',
        'color': 'color',
        'last_name': 'lastName',
        'first_name': 'firstName',
        'id': 'id',
        'authy_id': 'authyId',
        'status': 'status',
        'created_at': 'createdAt',
        'credential': 'credential',
        'node_id': 'nodeId',
        'password': 'password'
    }

    def __init__(self, updated_at=None, email=None, url=None, is_super_admin=None, preferred_organization_id=None, color=None, last_name=None, first_name=None, id=None, authy_id=None, status=None, created_at=None, credential=None, node_id=None, password=None):  # noqa: E501
        """User - a model defined in OpenAPI"""  # noqa: E501

        self._updated_at = None
        self._email = None
        self._url = None
        self._is_super_admin = None
        self._preferred_organization_id = None
        self._color = None
        self._last_name = None
        self._first_name = None
        self._id = None
        self._authy_id = None
        self._status = None
        self._created_at = None
        self._credential = None
        self._node_id = None
        self._password = None
        self.discriminator = None

        self.updated_at = updated_at
        self.email = email
        self.url = url
        self.is_super_admin = is_super_admin
        if preferred_organization_id is not None:
            self.preferred_organization_id = preferred_organization_id
        self.color = color
        self.last_name = last_name
        self.first_name = first_name
        self.id = id
        self.authy_id = authy_id
        self.status = status
        self.created_at = created_at
        self.credential = credential
        self.node_id = node_id
        self.password = password

    @property
    def updated_at(self):
        """Gets the updated_at of this User.  # noqa: E501


        :return: The updated_at of this User.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this User.


        :param updated_at: The updated_at of this User.  # noqa: E501
        :type: datetime
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")  # noqa: E501

        self._updated_at = updated_at

    @property
    def email(self):
        """Gets the email of this User.  # noqa: E501


        :return: The email of this User.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this User.


        :param email: The email of this User.  # noqa: E501
        :type: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def url(self):
        """Gets the url of this User.  # noqa: E501


        :return: The url of this User.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this User.


        :param url: The url of this User.  # noqa: E501
        :type: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    @property
    def is_super_admin(self):
        """Gets the is_super_admin of this User.  # noqa: E501


        :return: The is_super_admin of this User.  # noqa: E501
        :rtype: bool
        """
        return self._is_super_admin

    @is_super_admin.setter
    def is_super_admin(self, is_super_admin):
        """Sets the is_super_admin of this User.


        :param is_super_admin: The is_super_admin of this User.  # noqa: E501
        :type: bool
        """
        if is_super_admin is None:
            raise ValueError("Invalid value for `is_super_admin`, must not be `None`")  # noqa: E501

        self._is_super_admin = is_super_admin

    @property
    def preferred_organization_id(self):
        """Gets the preferred_organization_id of this User.  # noqa: E501


        :return: The preferred_organization_id of this User.  # noqa: E501
        :rtype: int
        """
        return self._preferred_organization_id

    @preferred_organization_id.setter
    def preferred_organization_id(self, preferred_organization_id):
        """Sets the preferred_organization_id of this User.


        :param preferred_organization_id: The preferred_organization_id of this User.  # noqa: E501
        :type: int
        """

        self._preferred_organization_id = preferred_organization_id

    @property
    def color(self):
        """Gets the color of this User.  # noqa: E501


        :return: The color of this User.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this User.


        :param color: The color of this User.  # noqa: E501
        :type: str
        """
        if color is None:
            raise ValueError("Invalid value for `color`, must not be `None`")  # noqa: E501

        self._color = color

    @property
    def last_name(self):
        """Gets the last_name of this User.  # noqa: E501


        :return: The last_name of this User.  # noqa: E501
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this User.


        :param last_name: The last_name of this User.  # noqa: E501
        :type: str
        """
        if last_name is None:
            raise ValueError("Invalid value for `last_name`, must not be `None`")  # noqa: E501

        self._last_name = last_name

    @property
    def first_name(self):
        """Gets the first_name of this User.  # noqa: E501


        :return: The first_name of this User.  # noqa: E501
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this User.


        :param first_name: The first_name of this User.  # noqa: E501
        :type: str
        """
        if first_name is None:
            raise ValueError("Invalid value for `first_name`, must not be `None`")  # noqa: E501

        self._first_name = first_name

    @property
    def id(self):
        """Gets the id of this User.  # noqa: E501


        :return: The id of this User.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this User.


        :param id: The id of this User.  # noqa: E501
        :type: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def authy_id(self):
        """Gets the authy_id of this User.  # noqa: E501


        :return: The authy_id of this User.  # noqa: E501
        :rtype: int
        """
        return self._authy_id

    @authy_id.setter
    def authy_id(self, authy_id):
        """Sets the authy_id of this User.


        :param authy_id: The authy_id of this User.  # noqa: E501
        :type: int
        """
        if authy_id is None:
            raise ValueError("Invalid value for `authy_id`, must not be `None`")  # noqa: E501

        self._authy_id = authy_id

    @property
    def status(self):
        """Gets the status of this User.  # noqa: E501


        :return: The status of this User.  # noqa: E501
        :rtype: bool
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this User.


        :param status: The status of this User.  # noqa: E501
        :type: bool
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def created_at(self):
        """Gets the created_at of this User.  # noqa: E501


        :return: The created_at of this User.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this User.


        :param created_at: The created_at of this User.  # noqa: E501
        :type: datetime
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def credential(self):
        """Gets the credential of this User.  # noqa: E501


        :return: The credential of this User.  # noqa: E501
        :rtype: str
        """
        return self._credential

    @credential.setter
    def credential(self, credential):
        """Sets the credential of this User.


        :param credential: The credential of this User.  # noqa: E501
        :type: str
        """
        if credential is None:
            raise ValueError("Invalid value for `credential`, must not be `None`")  # noqa: E501

        self._credential = credential

    @property
    def node_id(self):
        """Gets the node_id of this User.  # noqa: E501


        :return: The node_id of this User.  # noqa: E501
        :rtype: str
        """
        return self._node_id

    @node_id.setter
    def node_id(self, node_id):
        """Sets the node_id of this User.


        :param node_id: The node_id of this User.  # noqa: E501
        :type: str
        """
        if node_id is None:
            raise ValueError("Invalid value for `node_id`, must not be `None`")  # noqa: E501

        self._node_id = node_id

    @property
    def password(self):
        """Gets the password of this User.  # noqa: E501


        :return: The password of this User.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this User.


        :param password: The password of this User.  # noqa: E501
        :type: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, User):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
