# coding: utf-8

"""
    Blackfynn Swagger

    Swagger documentation for the Blackfynn api  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class WrappedPackage(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'updated_at': 'datetime',
        'state': 'PackageState',
        'dataset_id': 'str',
        'package_type': 'PackageType',
        'id': 'str',
        'created_at': 'datetime',
        'parent_id': 'int'
    }

    attribute_map = {
        'name': 'name',
        'updated_at': 'updatedAt',
        'state': 'state',
        'dataset_id': 'datasetId',
        'package_type': 'packageType',
        'id': 'id',
        'created_at': 'createdAt',
        'parent_id': 'parentId'
    }

    def __init__(self, name=None, updated_at=None, state=None, dataset_id=None, package_type=None, id=None, created_at=None, parent_id=None):  # noqa: E501
        """WrappedPackage - a model defined in OpenAPI"""  # noqa: E501

        self._name = None
        self._updated_at = None
        self._state = None
        self._dataset_id = None
        self._package_type = None
        self._id = None
        self._created_at = None
        self._parent_id = None
        self.discriminator = None

        self.name = name
        self.updated_at = updated_at
        self.state = state
        self.dataset_id = dataset_id
        self.package_type = package_type
        self.id = id
        self.created_at = created_at
        if parent_id is not None:
            self.parent_id = parent_id

    @property
    def name(self):
        """Gets the name of this WrappedPackage.  # noqa: E501


        :return: The name of this WrappedPackage.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this WrappedPackage.


        :param name: The name of this WrappedPackage.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def updated_at(self):
        """Gets the updated_at of this WrappedPackage.  # noqa: E501


        :return: The updated_at of this WrappedPackage.  # noqa: E501
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this WrappedPackage.


        :param updated_at: The updated_at of this WrappedPackage.  # noqa: E501
        :type: datetime
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")  # noqa: E501

        self._updated_at = updated_at

    @property
    def state(self):
        """Gets the state of this WrappedPackage.  # noqa: E501


        :return: The state of this WrappedPackage.  # noqa: E501
        :rtype: PackageState
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this WrappedPackage.


        :param state: The state of this WrappedPackage.  # noqa: E501
        :type: PackageState
        """
        if state is None:
            raise ValueError("Invalid value for `state`, must not be `None`")  # noqa: E501

        self._state = state

    @property
    def dataset_id(self):
        """Gets the dataset_id of this WrappedPackage.  # noqa: E501


        :return: The dataset_id of this WrappedPackage.  # noqa: E501
        :rtype: str
        """
        return self._dataset_id

    @dataset_id.setter
    def dataset_id(self, dataset_id):
        """Sets the dataset_id of this WrappedPackage.


        :param dataset_id: The dataset_id of this WrappedPackage.  # noqa: E501
        :type: str
        """
        if dataset_id is None:
            raise ValueError("Invalid value for `dataset_id`, must not be `None`")  # noqa: E501

        self._dataset_id = dataset_id

    @property
    def package_type(self):
        """Gets the package_type of this WrappedPackage.  # noqa: E501


        :return: The package_type of this WrappedPackage.  # noqa: E501
        :rtype: PackageType
        """
        return self._package_type

    @package_type.setter
    def package_type(self, package_type):
        """Sets the package_type of this WrappedPackage.


        :param package_type: The package_type of this WrappedPackage.  # noqa: E501
        :type: PackageType
        """
        if package_type is None:
            raise ValueError("Invalid value for `package_type`, must not be `None`")  # noqa: E501

        self._package_type = package_type

    @property
    def id(self):
        """Gets the id of this WrappedPackage.  # noqa: E501


        :return: The id of this WrappedPackage.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this WrappedPackage.


        :param id: The id of this WrappedPackage.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def created_at(self):
        """Gets the created_at of this WrappedPackage.  # noqa: E501


        :return: The created_at of this WrappedPackage.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this WrappedPackage.


        :param created_at: The created_at of this WrappedPackage.  # noqa: E501
        :type: datetime
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def parent_id(self):
        """Gets the parent_id of this WrappedPackage.  # noqa: E501


        :return: The parent_id of this WrappedPackage.  # noqa: E501
        :rtype: int
        """
        return self._parent_id

    @parent_id.setter
    def parent_id(self, parent_id):
        """Sets the parent_id of this WrappedPackage.


        :param parent_id: The parent_id of this WrappedPackage.  # noqa: E501
        :type: int
        """

        self._parent_id = parent_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WrappedPackage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
