openapi: 3.0.0
info:
  version: '2.0.0'
  title: 'dsm-api'
  description: 'dsm api'

paths:
  /:
    get:
      operationId: health_check
      responses:
        '200':
          description: service health evaluated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileMetaData'
        default:
          $ref: '#/components/responses/DefaultErrorResponse'
          
  /files/metadata:
    get:
      summary: Get Files Metadata
      operationId: get_files_metadata
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FileMetaData'
                  
  /files/{fileId}/metadata:
    get:
      summary: Get File Metadata
      operationId: get_file_metadata
      parameters:
      - name: fileId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: 'file meta data'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileMetaData'
    patch:
      summary: Update File Metadata
      operationId: update_file_meta_data
      parameters:
      - name: fileId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: ''
          content:
             application/json:
              schema:
                $ref: '#/components/schemas/FileMetaData'
      requestBody:
        $ref: '#/components/requestBodies/FileMetaData'
        
  /files/{fileId}:
    get:
      summary: Donwload File
      operationId: download_file
      parameters:
      - name: fileId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/FileMetaData'
    put:
      summary: Upload File
      operationId: upload_file
      parameters:
      - name: fileId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: ''
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/FileMetaData'
      requestBody:
        $ref: '#/components/requestBodies/FileMetaData'
    delete:
      summary: Delte File
      operationId: delete_file
      parameters:
      - name: fileId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '204':
          description: ''

components:
  schemas:
    HealthInfo:
      type: object
      properties:
        name:
          type: string
          example: dsm service
        status:
          type: string
          example: RUNNING
        version:
          type: string
          example: 1.0.0-dev
        last_access:
          type: number
          example: 123.122
          
    ErrorModel:
      type: object
      properties:
        errors:
          type: array
          items:
              type: string
              
    FileMetaData:
      type: object
      properties:
        filename:
          type: string
          example: test.txt
        version:
          type: string
          example: 1.0
        last_accessed:
          type: number
          example: 123.122
        owner:
          type: string
          format: uuid
        storage_location:
          type: string
          example : simcore.s3
  
  d:
    FileMetaData:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FileMetaData'
      
  responses:
    DefaultErrorResponse:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorModel'

# Added by API Auto Mocking Plugin
servers:
  - description: Default server
    url: http://{host}:{port}/{version}
    variables:
      host:
        default: 'localhost'
      port:
        default: '8080'
      version:
        default: v1
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/mguidon/dsm/2.0.0