---
version: "1.0"
app:
  host: 127.0.0.1
  port: 8080
  log_level: DEBUG
  testing: True
postgres:
  database: ${POSTGRES_DB}
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  host: localhost
  port: 5432
  minsize: 1
  maxsize: 5
  endpoint: ${POSTGRES_ENDPOINT}
s3:
  endpoint: ${S3_ENDPOINT}
  access_key: ${S3_ACCESS_KEY}
  secret_key: ${S3_SECRET_KEY}
  bucket_name: ${S3_BUCKET_NAME}
...
